
server:
  port: 8080

spring:
  application:
    name: mandi-tracker-api

  datasource:
    url: jdbc:postgresql://localhost:5432/mandi_tracker
    username: postgres
    password: Sandy

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
